// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiO6oX3AbguO0ZnWHNdzrBSggIq0yX90I',
    appId: '1:272055249962:web:9d6d5113e58d5274f7e753',
    messagingSenderId: '272055249962',
    projectId: 'monitoring-qc-168a8',
    authDomain: 'monitoring-qc-168a8.firebaseapp.com',
    storageBucket: 'monitoring-qc-168a8.firebasestorage.app',
    measurementId: 'G-RVT3JKJ2TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwhoqrNU8-ObtJSOtjL2R6ngipIr3_c8',
    appId: '1:272055249962:android:08dddcd933daf673f7e753',
    messagingSenderId: '272055249962',
    projectId: 'monitoring-qc-168a8',
    storageBucket: 'monitoring-qc-168a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCe0i6xSrMSVk3xEm6zwWSBr4LWRh6XIk',
    appId: '1:272055249962:ios:4aec5de6faf63cbdf7e753',
    messagingSenderId: '272055249962',
    projectId: 'monitoring-qc-168a8',
    storageBucket: 'monitoring-qc-168a8.firebasestorage.app',
    iosBundleId: 'com.example.monitoringng2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCe0i6xSrMSVk3xEm6zwWSBr4LWRh6XIk',
    appId: '1:272055249962:ios:4aec5de6faf63cbdf7e753',
    messagingSenderId: '272055249962',
    projectId: 'monitoring-qc-168a8',
    storageBucket: 'monitoring-qc-168a8.firebasestorage.app',
    iosBundleId: 'com.example.monitoringng2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiO6oX3AbguO0ZnWHNdzrBSggIq0yX90I',
    appId: '1:272055249962:web:7ed7740a72a5ea33f7e753',
    messagingSenderId: '272055249962',
    projectId: 'monitoring-qc-168a8',
    authDomain: 'monitoring-qc-168a8.firebaseapp.com',
    storageBucket: 'monitoring-qc-168a8.firebasestorage.app',
    measurementId: 'G-S918J6VL73',
  );

}